<?php

namespace Neoan3\Components;

use Neoan3\Frame\Rbm;

/**
 * Class ActiveParticipation
 * Generated by neoan3-cli
 * @package Neoan3\Components
 */

class ActiveParticipation extends Rbm
{
    /**
     * @var array
     */
    private $vueComponents = ['contactus'];
    
    /**
     * init route 
     */
    function init()
    {
        $this
            ->hook('main', 'activeParticipation', [])
            ->vueComponents($this->vueComponents, [])
            ->output();
    }
}
