<?php

namespace Neoan3\Components;

use Neoan3\Frame\Rbm;

/**
 * Class AnnounceTool
 * Generated by neoan3-cli
 * @package Neoan3\Components
 */

class Announcetool extends Rbm
{
    /**
     * @var array
     */
    private $vueComponents = ['announcetool', 'contactus'];
    
    /**
     * init route 
     */
    function init()
    {
        $this
            ->hook('main', 'announcetool', [])
            ->addHead('title', 'Red Banner Media, LLC | Web Development Company | Announcement Tool')
            ->addHead('meta', [
                'name'=>'description',
                'content'=>'The announcement tool from Red Banner Media, LLC. Update your company web site with just a 
                quick copy and paste.'
            ])
            ->includeJs(base . 'asset/rbm-modal-component.min.js')
            ->vueComponents($this->vueComponents, [])
            ->output();
    }

    /**
     * @var array of dependencies as strings
     * NOTE: only global params can be passed in
     */
    private static array $requiredComponents = [];

    /**
     * This function is called by the RBM frame
     *
     * @return array
     */
    static function dependencies()
    {
        return self::$requiredComponents;
    }
}

