<?php

namespace Neoan3\Components;

use Neoan3\Frame\Rbm;

/**
 * Class Cdnlink
 * Generated by neoan3-cli
 * @package Neoan3\Components
 */

class Cdnlink extends Rbm
{
    /**
     * init route 
     */
    function init()
    {
        header('Content-type:application/javascript');
        echo file_get_contents(base . 'asset/rbm-modal-component.min.js');
        exit();
    }
}
