<?php

namespace Neoan3\Components;

use Neoan3\Frame\Rbm;

/**
 * Class Home
 * Generated by neoan3-cli
 * @package Neoan3\Components
 */

class Home extends Rbm
{
    /**
     * @var array
     */
    private array $vueComponents = ['home', 'rbmcard', 'contactus'];
    
    /**
     * init route 
     */
    function init()
    {
        $this
            ->hook('main', 'home', [])
            ->addHead('title', 'Red Banner Media, LLC | Web Development Company in Rochester, NY')
            ->addHead('meta', [
                'name'=>'description',
                'content'=>'Red Banner Media, LLC brings web technologies to your business. We develop websites, web apps
                and tools that help you run your business.'
            ])
            ->vueComponents($this->vueComponents, [])
            ->output();
    }

    /**
     * @var array of dependencies as strings
     * NOTE: only global params can be passed in
     */
    private static array $requiredComponents = [];

    /**
     * This function is called by the RBM frame
     *
     * @return array
     */
    static function dependencies()
    {
        return self::$requiredComponents;
    }
}

