<?php

namespace Neoan3\Components;

use Neoan3\Frame\Rbm;

/**
 * Class Home
 * Generated by neoan3-cli
 * @package Neoan3\Components
 */

class Home extends Rbm
{
    /**
     * @var array
     */
    private array $vueComponents = ['home', 'rbmcard', 'contactus', 'rbmfooter'];
    
    /**
     * init route 
     */
    function init()
    {
        $this
            ->hook('main', 'home', [])
            ->vueComponents($this->vueComponents, [])
            ->output();
    }

    /**
     * @var array of dependencies as strings
     * NOTE: only global params can be passed in
     */
    private static array $requiredComponents = [];

    /**
     * This function is called by the RBM frame
     *
     * @return array
     */
    static function dependencies()
    {
        return self::$requiredComponents;
    }
}

