<?php

namespace Neoan3\Components;

use Neoan3\Frame\Rbm;

/**
 * Class {{name}}
 * Generated by neoan3-cli
 * @package Neoan3\Components
 */

class {{name}} extends Rbm
{
    /**
     * @var array
     */
    private $vueComponents = [];
    
    /**
     * init route 
     */
    function init()
    {
        $this
            ->hook('main', '{{name.camel}}', [])
            ->vueComponents($this->vueComponents, [])
            ->output();
    }
}
